### ISSUE TITLE
Unfortunately it doesn't work

### ISSUE THREAD

**Issue by peterpernhofer** [poipoi300/auto-sd-krita-ext-xl#10]
While starting Krita, the following error appears three time:

```
C:\Program Files\Krita (x64)\lib\krita-python-libs\krita\dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
14 super(DockWidgetFactory, self).init(_id, _dockPosition)
15 self.klass = _klass
16
17 def createDockWidget(self):
18 return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'krita_diff.docker.create_docker..Docker'>
etc etc . . .
```

It's the same issue as in the original branch: look here for full detailed description: https://github.com/Interpause/auto-sd-paint-ext/issues/165

Krita v. 5.2.2
Auto1111 v.1.7.0

**Comment by Miraihi** [comment]
https://github.com/Interpause/auto-sd-paint-ext/issues/165#issuecomment-1869562034

**Comment by poipoi300** [comment]
Thanks for opening an issue, I'll check this out tomorrow.

**Comment by poipoi300** [comment]
I am not having this issue. Can you try the latest Krita release (5.2.2)? Also delete your config in %APPDATA%\krita on windows. The files are ```krita_diff_plugin.ini``` and ```krita_diff_plugin_scripts.ini```

**Comment by poipoi300** [comment]
My bad just saw you're already on the latest release. For some reason I remembered 5.2.1
Edit: Ah, it was 5.2.1 in the linked issue.

**Comment by poipoi300** [comment]
Will close the issue tomorrow without clear steps to reproduce.

**Comment by peterpernhofer** [comment]
Sorry for the late reply. Yes. After deleting the config files it seems to work. The error message still appears non-stop, but that's probably Krita's fault. But I now have all docks available. Thank you :-)

**Comment by poipoi300** [comment]
That's good to hear, I'm not sure what those error messages you're mentioning refer to, as I'm currently aware of those in the console and those that sometimes pop up when closing krita, but none that would be "non-stop". I would appreciate a separate, detailed (including how to reproduce + screenshots), issue on those if you don't mind.

As for the responsibility, the errors pertaining to scripts in the console is 100% the plugin, the errors that pop up when closing krita I'm not sure, but it might be possible to fix from our point of view. Any other errors are likely not krita's fault either.

**Comment by peterpernhofer** [comment]
The error messages appears while Krita is open. However, as non-stopping messages (non-modal).
I can gladly test that, but only in 3 weeks, as I'm flying to Mauritius today :-)

**Comment by poipoi300** [comment]
Alright have a nice trip 😀
