### ISSUE TITLE
[bug] issue with seed

### ISSUE THREAD

**Issue by Rogal80** [poipoi300/auto-sd-krita-ext-xl#5]
**Describe the bug**
Hi , 

After installation, it appears that the seed doesn't work for me.,

**Screenshots**

- Screenshot of backend console output
- Status bar message when error occured
- All contents of Krita error popup (if any)

**Desktop (please complete the following information):**
 - OS:Windows
 - WebUI commit revision [5ef669de080814067961f28357256e8fe27544f4]
 - Extension commit revision (98aff574d2fe6bcc2b5f7b3878566d725da84b34)

**Additional context**

**Comment by poipoi300** [comment]
Thanks for opening the issue, I probably wouldn't have noticed without that 😅

It seems the new A41 version doesn't take a seed in the function parameters anymore...

Might be something I can add in through *args or I might need to set some shared variable. I'll check this out soon.

**Comment by poipoi300** [comment]
Hey I have not made 0 progress on this. It's quite important to be fixed obviously. 

I've started searching in the A41 repo to see how they actually set the seed but I have not found it yet. My dealings with that code base had been limited to images.py and around that, so I really don't know much about the codebase as a whole.

I did try to pass the seed through *args and obviously it was never going to be that easy 😂
Maybe I can pass it to override parameters... 💀

If I can and it works, then that would be the temp fix until I find the proper way. Will have a little time tomorrow for this.

**Comment by poipoi300** [comment]
Good news, I managed to get seeds working again. The fix right now is to completely sidestep the txt2img/img2img functions and do what they do on the inside from the extension backend. This gives us access to set the seed on the processing object before we generate an image with it. It may give us more freedom later down the line as well, but we'll see.

The repo will be updated soon, I've tested with txt2img only, but need to do the same for img2img, and then clean up some stuff. Unfortunately I don't think the robustness fix can be carried over so I do not know what this means for SD.Next support.

**Comment by poipoi300** [comment]
Currently having some issues getting img2img to work, that's all the time I had for now (it's almost 3am). I may just push the txt2img fix with the old img2img (seeds not working) if I can't get it done reasonably quickly.

**Comment by poipoi300** [comment]
A lot more work than I thought, lol. I got more familiar with the code at least though. I also feel like I'm closer to being able to fix the errors that pop up in the console whenever we generate something.

**Comment by poipoi300** [comment]
Can confirm this broke SD.Next support. I'll look into it next weekend.
